In [2]:
!pip install -q spacy pandas nltk networkx matplotlib
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 90.5 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

folder_path = "/content/drive/MyDrive/RST"

if os.path.exists(folder_path):
    print("Files inside the RST folder:\n")
    for file in os.listdir(folder_path):
        print(file)
else:
    print("Folder not found:", folder_path)

Files inside the RST folder:

bbc article.txt
AI generated.txt

In [5]:
import os


bbc_file = "/content/drive/MyDrive/RST/bbc article.txt"


if os.path.exists(bbc_file):
    print("BBC article found.\n")


    with open(bbc_file, "r", encoding="utf-8") as file:
        bbc_text = file.read()


    print(bbc_text[:2000])

else:
    print("File not found:", bbc_file)

BBC article found.

Navin Singh Khadka
Environment correspondent
Camels are famously known as the ships of the desert, but even these hardy animals are not being spared from the extremes of rising temperatures in Africa.
The Afar region of north-eastern Ethiopia is one of the hottest and driest places on Earth, where nomads often lead camel caravans carrying salt through the desert.
"I can see my camels suffering from extreme heat," Ali Umer, a camel herder from Semera in Afar, told the BBC.

"They get blisters on their feet, their eyes become watery and the hot sand burns their skin and eats up their hair when they are sitting," said the 40-year-old who owns around 500 camels.
"Within the past one month I have lost eight camel calves
because of the extreme heat, it has become much more intense and difficult.
"Even the wind, which used to bring cool air, now carries heat," he said, adding he had noticed these drastic changes in the temperature in recent years.
He is not alone in his observations: scientists, animal welfare workers and various studies all mention stress, fatigue, dehydration, disease prevalence as direct impacts of extreme heat.
The higher temperatures also indirectly make camels suffer by causing severe loss of water, vegetation, and reduced shaded areas.

North Africa and the Horn of Africa host around 80% of the world's largest population of dromedary camels - those with one hump.
Over the years, farmers and cattle herders in these regions have switched to these animals because of their resilience to harsh heat and drought conditions.
But a study based on the perception of camel herders in southern Ethiopia, published in 2025, showed that high temperatures and climate variability had had a detrimental impact on camel herd health.
"Respondents reported that climate change and variability have affected camels' health, productivity, and reproductive performance," it said.
In neighbouring Somalia, the situation appears to be more serious. Research published in June has s

In [6]:

!pip install -q spacy
!python -m spacy download en_core_web_sm

import spacy
import pandas as pd


nlp = spacy.load("en_core_web_sm")


doc = nlp(bbc_text)


sentences = [
    sent.text.strip()
    for sent in doc.sents
    if sent.text.strip()
]


bbc_df = pd.DataFrame({
    "Unit_ID": range(1, len(sentences) + 1),
    "Text": sentences
})

print(f"Total possible RST units: {len(bbc_df)}")

bbc_df

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 55.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Total possible RST units: 41

    Unit_ID                                               Text
0         1  Navin Singh Khadka\nEnvironment correspondent\...
1         2  The Afar region of north-eastern Ethiopia is o...
2         3  "I can see my camels suffering from extreme he...
3         4  "They get blisters on their feet, their eyes b...
4         5  "Within the past one month I have lost eight c...
5         6  "Even the wind, which used to bring cool air, ...
6         7  He is not alone in his observations: scientist...
7         8  The higher temperatures also indirectly make c...
8         9  North Africa and the Horn of Africa host aroun...
9        10  Over the years, farmers and cattle herders in ...
10       11  But a study based on the perception of camel h...
11       12  "Respondents reported that climate change and ...
12       13  In neighbouring Somalia, the situation appears...
13       14  Research published in June has shown that drou...
14       15  The study included nearly 6,000 pastoral house...
15       16  Extreme heat is the main cause behind the drou...
16       17  An analysis by atmospheric scientists found th...
17       18  Veterinarians say they are treating more sick ...
18       19  "We are seeing significant increase in cases o...
19       20  "In the last two years, we have seen a more th...
20       21  "Disease prevalence among camels and reduced m...
21       22    A similar story is playing out in North Africa.
22       23  A study in Algeria, published this year, has s...
23       24  The World Meteorological Organization (WMO) sa...
24       25  It said a number of countries in the region an...
25       26  WMO's State of the Climate in Africa 2025 repo...
26       27  By doing that they avoid sweating and, combine...
27       28  "In many parts of the Sahara, summer temperatu...
28       29  Professor Abdelmadjid Chehma at the University...
29       30  "Our works show that prolonged day-and-night h...
30       31  "Their immune system suffers because such heat...
31       32  "For camels this means when heat stress sets i...
32       33  That leads to drop in milk production and also...
33       34  While extreme heat is the primary culprit, its...
34       35  This is why many herders in Ethiopia have move...
35       36  "And this is not the seasonal movement of the ...
36       37  The Horn of Africa has been recovering from th...
37       38  It said water prices in some parts of Somalia ...
38       39  Umer, the cattle herder in Afar, said he was w...
39       40    His concern is valid, according to Prof Chehma.
40       41  "While camels remain the livestock herders' la...

In [7]:
import re
import spacy
import pandas as pd


clean_text = bbc_text

clean_text = clean_text.replace("Navin Singh Khadka", "")
clean_text = clean_text.replace("Environment correspondent", "")


clean_text = re.sub(r'\n+', ' ', clean_text)
clean_text = re.sub(r'(\w)\.([A-Z])', r'\1. \2', clean_text)
clean_text = re.sub(r'(\d)%', r'\1%', clean_text)


doc = nlp(clean_text)

sentences = [
    sent.text.strip()
    for sent in doc.sents
    if sent.text.strip()
]


bbc_df = pd.DataFrame({
    "Unit_ID": range(1, len(sentences) + 1),
    "Text": sentences
})

print(f"Total units: {len(bbc_df)}")
bbc_df.head(30)

Total units: 42

    Unit_ID                                               Text
0         1  Camels are famously known as the ships of the ...
1         2  The Afar region of north-eastern Ethiopia is o...
2         3  "I can see my camels suffering from extreme he...
3         4  "They get blisters on their feet, their eyes b...
4         5  "Within the past one month I have lost eight c...
5         6  "Even the wind, which used to bring cool air, ...
6         7  He is not alone in his observations: scientist...
7         8  The higher temperatures also indirectly make c...
8         9  North Africa and the Horn of Africa host aroun...
9        10  Over the years, farmers and cattle herders in ...
10       11  But a study based on the perception of camel h...
11       12  "Respondents reported that climate change and ...
12       13  In neighbouring Somalia, the situation appears...
13       14  Research published in June has shown that drou...
14       15  The study included nearly 6,000 pastoral house...
15       16  Extreme heat is the main cause behind the drou...
16       17  An analysis by atmospheric scientists found th...
17       18  Veterinarians say they are treating more sick ...
18       19  "We are seeing significant increase in cases o...
19       20  "In the last two years, we have seen a more th...
20       21  "Disease prevalence among camels and reduced m...
21       22    A similar story is playing out in North Africa.
22       23  A study in Algeria, published this year, has s...
23       24  The World Meteorological Organization (WMO) sa...
24       25  It said a number of countries in the region an...
25       26  WMO's State of the Climate in Africa 2025 repo...
26       27  Experts say camels comfortably beat the heat u...
27       28  By doing that they avoid sweating and, combine...
28       29  "In many parts of the Sahara, summer temperatu...
29       30  Professor Abdelmadjid Chehma at the University...

In [8]:


bbc_rst = bbc_df.copy()


bbc_rst["Role"] = ""
bbc_rst["Relation"] = ""
bbc_rst["Confidence"] = 0.0


for i, row in bbc_rst.iterrows():
    text = row["Text"].lower()


    if any(word in text for word in [
        "study", "research", "scientists", "veterinarians",
        "experts", "analysis", "report", "published"
    ]):
        bbc_rst.at[i, "Role"] = "Satellite"
        bbc_rst.at[i, "Relation"] = "Evidence"
        bbc_rst.at[i, "Confidence"] = 0.80


    elif any(phrase in text for phrase in [
        "because of", "as a result", "cause behind",
        "due to", "causing"
    ]):
        bbc_rst.at[i, "Role"] = "Satellite"
        bbc_rst.at[i, "Relation"] = "Cause"
        bbc_rst.at[i, "Confidence"] = 0.75


    elif any(word in text for word in [
        "but", "however", "although", "while"
    ]):
        bbc_rst.at[i, "Role"] = "Nucleus"
        bbc_rst.at[i, "Relation"] = "Contrast"
        bbc_rst.at[i, "Confidence"] = 0.70


    elif any(word in text for word in [
        "region", "africa", "ethiopia", "somalia",
        "kenya", "north africa"
    ]):
        bbc_rst.at[i, "Role"] = "Satellite"
        bbc_rst.at[i, "Relation"] = "Background"
        bbc_rst.at[i, "Confidence"] = 0.65


    else:
        bbc_rst.at[i, "Role"] = "Satellite"
        bbc_rst.at[i, "Relation"] = "Elaboration"
        bbc_rst.at[i, "Confidence"] = 0.50


pd.set_option("display.max_colwidth", 100)
bbc_rst

,Unit_ID,Text,Role,Relation,Confidence
0,1,"Camels are famously known as the ships of the desert, but even these hardy animals are not being...",Nucleus,Contrast,0.70
1,2,"The Afar region of north-eastern Ethiopia is one of the hottest and driest places on Earth, wher...",Satellite,Background,0.65
2,3,"""I can see my camels suffering from extreme heat,"" Ali Umer, a camel herder from Semera in Afar,...",Satellite,Elaboration,0.50
3,4,"""They get blisters on their feet, their eyes become watery and the hot sand burns their skin and...",Satellite,Elaboration,0.50
4,5,"""Within the past one month I have lost eight camel calves because of the extreme heat, it has be...",Satellite,Cause,0.75
5,6,"""Even the wind, which used to bring cool air, now carries heat,"" he said, adding he had noticed ...",Satellite,Elaboration,0.50
6,7,"He is not alone in his observations: scientists, animal welfare workers and various studies all ...",Satellite,Evidence,0.80
7,8,"The higher temperatures also indirectly make camels suffer by causing severe loss of water, vege...",Satellite,Cause,0.75
8,9,North Africa and the Horn of Africa host around 80% of the world's largest population of dromeda...,Satellite,Background,0.65
9,10,"Over the years, farmers and cattle herders in these regions have switched to these animals becau...",Satellite,Cause,0.75
10,11,"But a study based on the perception of camel herders in southern Ethiopia, published in 2025, sh...",Satellite,Evidence,0.80
11,12,"""Respondents reported that climate change and variability have affected camels' health, producti...",Satellite,Evidence,0.80
12,13,"In neighbouring Somalia, the situation appears to be more serious.",Satellite,Background,0.65
13,14,Research published in June has shown that drought-related camel mortality is a widespread crisis...,Satellite,Evidence,0.80
14,15,"The study included nearly 6,000 pastoral households and showed that the mortality was concentrat...",Satellite,Evidence,0.80
15,16,Extreme heat is the main cause behind the drought in the region although other factors like inad...,Satellite,Evidence,0.80
16,17,An analysis by atmospheric scientists found that high temperatures in the region were behind the...,Satellite,Evidence,0.80
17,18,Veterinarians say they are treating more sick camels and are seeing more deaths due to extreme h...,Satellite,Evidence,0.80
18,19,"""We are seeing significant increase in cases of hyperthermia in camels as a result of which they...",Satellite,Cause,0.75
19,20,"""In the last two years, we have seen a more than 15% increase in camel deaths in our county due ...",Satellite,Cause,0.75
20,21,"""Disease prevalence among camels and reduced milk yield from them are as a result of climate cha...",Satellite,Evidence,0.80
21,22,A similar story is playing out in North Africa.,Satellite,Background,0.65
22,23,"A study in Algeria, published this year, has shown a significant increase in camel deaths during...",Satellite,Evidence,0.80
23,24,The World Meteorological Organization (WMO) says extreme heat events have become a common phenom...,Satellite,Background,0.65
24,25,It said a number of countries in the region and the Middle East reported temperatures above 50C ...,Satellite,Evidence,0.80
25,26,WMO's State of the Climate in Africa 2025 report said North Africa recorded the most rapid warmi...,Satellite,Evidence,0.80
26,27,Experts say camels comfortably beat the heat up to around 40C by mainly allowing their body temp...,Satellite,Evidence,0.80
27,28,"By doing that they avoid sweating and, combined with concentrated urine and dry faeces, it helps...",Nucleus,Contrast,0.70
28,29,"""In many parts of the Sahara, summer temperatures now frequently exceed 50C, increasing the risk...",Satellite,Elaboration,0.50
29,30,"Professor Abdelmadjid Chehma at the University of Ghardaia in Algeria, who has conducted experim...",Satellite,Elaboration,0.50
30,31,"""Our works show that prolonged day-and-night heat above 41 to 45C directly attack their cells,"" ...",Satellite,Elaboration,0.50
31,32,"""Their immune system suffers because such heat levels damage their white blood cells and other c...",Satellite,Cause,0.75
32,33,"""For camels this means when heat stress sets in, their metabolism slows down to limit internal h...",Satellite,Elaboration,0.50
33,34,That leads to drop in milk production and also causes reproductive disordersProfessor Mohammed e...,Satellite,Cause,0.75
34,35,"While extreme heat is the primary culprit, its impacts become severe when other factors like los...",Satellite,Evidence,0.80
35,36,"This is why many herders in Ethiopia have moved their camels from the northern region, where the...",Satellite,Evidence,0.80
36,37,"""And this is not the seasonal movement of the herders,"" said Daniel Gelan, professor and pastora...",Satellite,Evidence,0.80
37,38,The Horn of Africa has been recovering from the longest and most severe recorded drought spannin...,Nucleus,Contrast,0.70
38,39,"It said water prices in some parts of Somalia had risen by more than 2,000% because of the drought.",Satellite,Cause,0.75
39,40,"Umer, the cattle herder in Afar, said he was worried that an outbreak of disease could start kil...",Satellite,Elaboration,0.50
40,41,"His concern is valid, according to Prof Chehma.",Satellite,Elaboration,0.50
41,42,"""While camels remain the livestock herders' last line of defence against the desert, the unprece...",Nucleus,Contrast,0.70

In [13]:

markdown_table = bbc_rst.to_markdown(index=False)


print(markdown_table)

|   Unit_ID | Text                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Role      | Relation    |   Confidence |
|----------:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------|:------------|-------------:|
|         1 | Camels are famously known as the ships of the desert, but even these hardy animals are not being spared from the extremes of rising temperatures in Africa.                                                                                                                                                                                                                                                                                           | Nucleus   | Contrast    |         0.7  |
|         2 | The Afar region of north-eastern Ethiopia is one of the hottest and driest places on Earth, where nomads often lead camel caravans carrying salt through the desert.                                                                                                                                                                                                                                                                                  | Satellite | Background  |         0.65 |
|         3 | "I can see my camels suffering from extreme heat," Ali Umer, a camel herder from Semera in Afar, told the BBC.                                                                                                                                                                                                                                                                                                                                        | Satellite | Elaboration |         0.5  |
|         4 | "They get blisters on their feet, their eyes become watery and the hot sand burns their skin and eats up their hair when they are sitting," said the 40-year-old who owns around 500 camels.                                                                                                                                                                                                                                                          | Satellite | Elaboration |         0.5  |
|         5 | "Within the past one month I have lost eight camel calves because of the extreme heat, it has become much more intense and difficult.                                                                                                                                                                                                                                                                                                                 | Satellite | Cause       |         0.75 |
|         6 | "Even the wind, which used to bring cool air, now carries heat," he said, adding he had noticed these drastic changes in the temperature in recent years.                                                                                                                                                                                                                                                                                             | Satellite | Elaboration |         0.5  |
|         7 | He is not alone in his observations: scientists, animal welfare workers and various studies all mention stress, fatigue, dehydration, disease prevalence as direct impacts of extreme heat.                                                                                                                                                                                                                                                           | Satellite | Evidence    |         0.8  |
|         8 | The higher temperatures also indirectly make camels suffer by causing severe loss of water, vegetation, and reduced shaded areas.                                                                                                                                                                                                                                                                                                                     | Satellite | Cause       |         0.75 |
|         9 | North Africa and the Horn of Africa host around 80% of the world's largest population of dromedary camels - those with one hump.                                                                                                                                                                                                                                                                                                                      | Satellite | Background  |         0.65 |
|        10 | Over the years, farmers and cattle herders in these regions have switched to these animals because of their resilience to harsh heat and drought conditions.                                                                                                                                                                                                                                                                                          | Satellite | Cause       |         0.75 |
|        11 | But a study based on the perception of camel herders in southern Ethiopia, published in 2025, showed that high temperatures and climate variability had had a detrimental impact on camel herd health.                                                                                                                                                                                                                                                | Satellite | Evidence    |         0.8  |
|        12 | "Respondents reported that climate change and variability have affected camels' health, productivity, and reproductive performance," it said.                                                                                                                                                                                                                                                                                                         | Satellite | Evidence    |         0.8  |
|        13 | In neighbouring Somalia, the situation appears to be more serious.                                                                                                                                                                                                                                                                                                                                                                                    | Satellite | Background  |         0.65 |
|        14 | Research published in June has shown that drought-related camel mortality is a widespread crisis, affecting nearly46% of camel-owning households.                                                                                                                                                                                                                                                                                                     | Satellite | Evidence    |         0.8  |
|        15 | The study included nearly 6,000 pastoral households and showed that the mortality was concentrated in northern regions, with Sool reporting a "staggering mortality rate of nearly 73%".                                                                                                                                                                                                                                                              | Satellite | Evidence    |         0.8  |
|        16 | Extreme heat is the main cause behind the drought in the region although other factors like inadequate veterinary services and animal management make things worse, experts say.                                                                                                                                                                                                                                                                      | Satellite | Evidence    |         0.8  |
|        17 | An analysis by atmospheric scientists found that high temperatures in the region were behind the 2021-22 drought, as extreme heat makes water from soil and water bodies turn into vapour and plants release water in them into air as vapour.                                                                                                                                                                                                        | Satellite | Evidence    |         0.8  |
|        18 | Veterinarians say they are treating more sick camels and are seeing more deaths due to extreme heat and drought.                                                                                                                                                                                                                                                                                                                                      | Satellite | Evidence    |         0.8  |
|        19 | "We are seeing significant increase in cases of hyperthermia in camels as a result of which they get multiple infections," Hassan Nuya Guyo, a veterinary officer in Marsabit county in north-eastern Kenya bordering Ethiopia, told the BBC.                                                                                                                                                                                                         | Satellite | Cause       |         0.75 |
|        20 | "In the last two years, we have seen a more than 15% increase in camel deaths in our county due to extreme heat.                                                                                                                                                                                                                                                                                                                                      | Satellite | Cause       |         0.75 |
|        21 | "Disease prevalence among camels and reduced milk yield from them are as a result of climate change impacts including heat stress, according to another study conducted in the Horn of Africa.                                                                                                                                                                                                                                                        | Satellite | Evidence    |         0.8  |
|        22 | A similar story is playing out in North Africa.                                                                                                                                                                                                                                                                                                                                                                                                       | Satellite | Background  |         0.65 |
|        23 | A study in Algeria, published this year, has shown a significant increase in camel deaths during summer heatwaves"Time series analysis highlights significant seasonal mortality patterns, underscoring the need for targeted interventions during high-risk periods like peak summer months; such as strategic water provisioning, supplemental feeding, and enhanced disease monitoring," it said.                                                  | Satellite | Evidence    |         0.8  |
|        24 | The World Meteorological Organization (WMO) says extreme heat events have become a common phenomenon in several North African countries with heatwaves having increased with a clear upward trend since 1981.                                                                                                                                                                                                                                         | Satellite | Background  |         0.65 |
|        25 | It said a number of countries in the region and the Middle East reported temperatures above 50C in 2024.                                                                                                                                                                                                                                                                                                                                              | Satellite | Evidence    |         0.8  |
|        26 | WMO's State of the Climate in Africa 2025 report said North Africa recorded the most rapid warming of the six subregions - 0.43C per decade - between 1991 and 2025.                                                                                                                                                                                                                                                                                  | Satellite | Evidence    |         0.8  |
|        27 | Experts say camels comfortably beat the heat up to around 40C by mainly allowing their body temperature to fluctuate by several degrees throughout the day to deal with outside temperature.                                                                                                                                                                                                                                                          | Satellite | Evidence    |         0.8  |
|        28 | By doing that they avoid sweating and, combined with concentrated urine and dry faeces, it helps them minimise water loss, while their thick skin coat helps them ward off solar radiation"But camels can also experience heat stress when temperatures rise beyond their comfort range," said Dr Mohammed Bengoumi, a scientist with the UN's Food and Agriculture Organization (FAO), who specialises in camel health and works in North Africa.    | Nucleus   | Contrast    |         0.7  |
|        29 | "In many parts of the Sahara, summer temperatures now frequently exceed 50C, increasing the risk of severe heat stress, particularly when accompanied by reduced vegetation cover, water scarcity, and limited access to shade," he told the BBC.                                                                                                                                                                                                     | Satellite | Elaboration |         0.5  |
|        30 | Professor Abdelmadjid Chehma at the University of Ghardaia in Algeria, who has conducted experimental works on camels in the Sahara Desert, has a similar conclusion.                                                                                                                                                                                                                                                                                 | Satellite | Elaboration |         0.5  |
|        31 | "Our works show that prolonged day-and-night heat above 41 to 45C directly attack their cells," he told the BBC.                                                                                                                                                                                                                                                                                                                                      | Satellite | Elaboration |         0.5  |
|        32 | "Their immune system suffers because such heat levels damage their white blood cells and other cells because of stress, they [the cells] struggle to repair themselves and end up destroying themselves.                                                                                                                                                                                                                                              | Satellite | Cause       |         0.75 |
|        33 | "For camels this means when heat stress sets in, their metabolism slows down to limit internal heat production leading to sharp reduction in food intake resulting in lethargy and generalised fatigue.                                                                                                                                                                                                                                               | Satellite | Elaboration |         0.5  |
|        34 | That leads to drop in milk production and also causes reproductive disordersProfessor Mohammed el Khasmi, animal hydrobiology expert at the University of Casablanca in Morocco, has a long list of effects of heat stress he and his team have observed on camelsWeight loss, inflammation, muscle and bone related illnesses, chemical imbalance due to kidney malfunction, infectious diseases caused by parasites were a few among them, he said. | Satellite | Cause       |         0.75 |
|        35 | While extreme heat is the primary culprit, its impacts become severe when other factors like loss of vegetation and water, lack of shaded areas and inadequate veterinary services add up, experts say.                                                                                                                                                                                                                                               | Satellite | Evidence    |         0.8  |
|        36 | This is why many herders in Ethiopia have moved their camels from the northern region, where the animals were found historically, to the south where water and vegetation are relatively available, experts there say.                                                                                                                                                                                                                                | Satellite | Evidence    |         0.8  |
|        37 | "And this is not the seasonal movement of the herders," said Daniel Gelan, professor and pastoralist development researcher with Vision University in Ethiopia"They are leaving the northern region for good because they can no longer sustain camel herding there because of extreme heat and drought," he told the BBC.                                                                                                                            | Satellite | Evidence    |         0.8  |
|        38 | The Horn of Africa has been recovering from the longest and most severe recorded drought spanning from 2020 to 2023, but now it is seeing another round of the harsh condition, according to charity organisation Oxfam.                                                                                                                                                                                                                              | Nucleus   | Contrast    |         0.7  |

In [14]:

markdown_table = bbc_rst.to_markdown(index=False)


with open("bbc_rst_analysis.md", "w", encoding="utf-8") as f:
    f.write(markdown_table)


from google.colab import files
files.download("bbc_rst_analysis.md")

In [15]:

ai_path = "/content/drive/MyDrive/RST/AI generated.txt"

with open(ai_path, "r", encoding="utf-8") as f:
    ai_text = f.read()


ai_units = [u.strip() for u in ai_text.split("\n\n") if u.strip()]


ai_df = pd.DataFrame({
    "Unit_ID": range(1, len(ai_units) + 1),
    "Text": ai_units
})

ai_df

,Unit_ID,Text
0,1,Even camels can't cope: Africa's ships of the desert hit by rising temperatures
1,2,"For centuries, the camel has been the ultimate survivor of Africa's drylands — an animal so well..."
2,3,"The animal renowned as the ""ship of the desert"" evolved to withstand extreme temperatures, water..."
3,4,## A herder's changing world
4,5,"Hassan Abdi Nur has kept camels in Kenya's Marsabit County for most of his life, following a rou..."
5,6,"""My father used to know exactly when the rains would come and where the grass would be green,"" N..."
6,7,"Nur said he lost four camels during the drought that struck the region between 2020 and 2023, on..."
7,8,"""We always said the camel does not die of thirst like other animals,"" he said. ""But I have seen ..."
8,9,Herders in neighbouring Somalia and Ethiopia's Somali region describe similar experiences. In pa...
9,10,## What the evidence shows
10,11,Herders' testimony is increasingly backed by scientific data. Meteorological records for the Hor...
11,12,"Regional climate monitoring bodies, including IGAD's Climate Prediction and Applications Centre,..."
12,13,"""We used to think of camels as almost drought-proof animals,"" said Dr Amina Yusuf, a veterinary ..."
13,14,"Camel populations in parts of the Horn of Africa have continued to grow in absolute numbers, par..."
14,15,## Why heat is proving so damaging
15,16,"Camels are, by any measure, extraordinarily well suited to hot, dry environments. They can toler..."
16,17,"These adaptations, however, are calibrated to a particular range of conditions — conditions that..."
17,18,"""The issue is not simply that it is hot — deserts have always been hot,"" explained Professor Ber..."
18,19,"Reduced, less predictable rainfall also affects the quality and availability of forage. Camels a..."
19,20,## A problem across the region
20,21,While the Horn of Africa has drawn particular attention because of the severity of its recent dr...
21,22,"In Somalia, where camels are central to the rural economy and national identity, officials and a..."
22,23,"Further north, in parts of the Sahara and Sahel, herders and researchers describe a slower but c..."
23,24,"""What we are seeing is not confined to one country or one drought cycle,"" said Dr Yusuf. ""It is ..."
24,25,## The biological toll
25,26,Veterinarians and researchers point to several interlinked biological effects when camels are ex...
26,27,Dehydration is the most immediate concern. Although camels tolerate significant fluid loss compa...
27,28,"Heat stress also appears to suppress immune function, making camels more susceptible to disease...."
28,29,"Milk production, a critical resource for pastoralist households, is particularly sensitive to he..."
29,30,Reproductive performance is also affected. Camels already have long gestation periods and low re...
30,31,"Taken together, these effects — dehydration, disease, reduced milk yield, reproductive setbacks ..."
31,32,## Consequences beyond the herd
32,33,The implications extend well beyond individual animals. Camels underpin the economies of pastora...
33,34,"There are also social and cultural dimensions. In many pastoralist societies, camel ownership is..."
34,35,"""When people lose their camels, they are not just losing an economic asset,"" said Fatuma Ali War..."
35,36,## Looking ahead
36,37,Climate projections for the Horn of Africa generally point towards continued warming and greater...
37,38,Efforts to respond are already under way. Veterinary services in some areas have expanded mobile...
38,39,"""There is no single solution,"" said Professor Kiptoo. ""It will require better veterinary support..."
39,40,"Some researchers also point to the need for policies supporting herder mobility, noting that res..."
40,41,## A resilience under strain
41,42,"For Hassan Abdi Nur, the technical explanations matter less than what he sees on the ground. He ..."
42,43,"""We are not giving up on the camel,"" he said. ""It is still the best animal for this land. But we..."
43,44,His words capture the wider story now unfolding across Africa's drylands. The camel remains one ...

In [17]:


import re
import pandas as pd


ai_clean = ai_df[~ai_df["Text"].str.match(r"^##\s*", na=False)].copy()


ai_clean = ai_clean[ai_clean["Text"].str.strip() != ""]


ai_clean["Text"] = (
    ai_clean["Text"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)


ai_clean["Unit_ID"] = range(1, len(ai_clean) + 1)


ai_clean = ai_clean[["Unit_ID", "Text"]]


ai_clean

,Unit_ID,Text
0,1,Even camels can't cope: Africa's ships of the desert hit by rising temperatures
1,2,"For centuries, the camel has been the ultimate survivor of Africa's drylands — an animal so well..."
2,3,"The animal renowned as the ""ship of the desert"" evolved to withstand extreme temperatures, water..."
4,4,"Hassan Abdi Nur has kept camels in Kenya's Marsabit County for most of his life, following a rou..."
5,5,"""My father used to know exactly when the rains would come and where the grass would be green,"" N..."
6,6,"Nur said he lost four camels during the drought that struck the region between 2020 and 2023, on..."
7,7,"""We always said the camel does not die of thirst like other animals,"" he said. ""But I have seen ..."
8,8,Herders in neighbouring Somalia and Ethiopia's Somali region describe similar experiences. In pa...
10,9,Herders' testimony is increasingly backed by scientific data. Meteorological records for the Hor...
11,10,"Regional climate monitoring bodies, including IGAD's Climate Prediction and Applications Centre,..."
12,11,"""We used to think of camels as almost drought-proof animals,"" said Dr Amina Yusuf, a veterinary ..."
13,12,"Camel populations in parts of the Horn of Africa have continued to grow in absolute numbers, par..."
15,13,"Camels are, by any measure, extraordinarily well suited to hot, dry environments. They can toler..."
16,14,"These adaptations, however, are calibrated to a particular range of conditions — conditions that..."
17,15,"""The issue is not simply that it is hot — deserts have always been hot,"" explained Professor Ber..."
18,16,"Reduced, less predictable rainfall also affects the quality and availability of forage. Camels a..."
20,17,While the Horn of Africa has drawn particular attention because of the severity of its recent dr...
21,18,"In Somalia, where camels are central to the rural economy and national identity, officials and a..."
22,19,"Further north, in parts of the Sahara and Sahel, herders and researchers describe a slower but c..."
23,20,"""What we are seeing is not confined to one country or one drought cycle,"" said Dr Yusuf. ""It is ..."
25,21,Veterinarians and researchers point to several interlinked biological effects when camels are ex...
26,22,Dehydration is the most immediate concern. Although camels tolerate significant fluid loss compa...
27,23,"Heat stress also appears to suppress immune function, making camels more susceptible to disease...."
28,24,"Milk production, a critical resource for pastoralist households, is particularly sensitive to he..."
29,25,Reproductive performance is also affected. Camels already have long gestation periods and low re...
30,26,"Taken together, these effects — dehydration, disease, reduced milk yield, reproductive setbacks ..."
32,27,The implications extend well beyond individual animals. Camels underpin the economies of pastora...
33,28,"There are also social and cultural dimensions. In many pastoralist societies, camel ownership is..."
34,29,"""When people lose their camels, they are not just losing an economic asset,"" said Fatuma Ali War..."
36,30,Climate projections for the Horn of Africa generally point towards continued warming and greater...
37,31,Efforts to respond are already under way. Veterinary services in some areas have expanded mobile...
38,32,"""There is no single solution,"" said Professor Kiptoo. ""It will require better veterinary support..."
39,33,"Some researchers also point to the need for policies supporting herder mobility, noting that res..."
41,34,"For Hassan Abdi Nur, the technical explanations matter less than what he sees on the ground. He ..."
42,35,"""We are not giving up on the camel,"" he said. ""It is still the best animal for this land. But we..."
43,36,His words capture the wider story now unfolding across Africa's drylands. The camel remains one ...

In [18]:


ai_rst = ai_clean.copy()

ai_rst["Role"] = ""
ai_rst["Relation"] = ""
ai_rst["Confidence"] = 0.0

for i, row in ai_rst.iterrows():
    text = row["Text"].lower()


    if any(word in text for word in [
        "study", "research", "scientists", "veterinarians",
        "experts", "analysis", "report", "published",
        "data", "researcher", "according to"
    ]):
        ai_rst.at[i, "Role"] = "Satellite"
        ai_rst.at[i, "Relation"] = "Evidence"
        ai_rst.at[i, "Confidence"] = 0.80


    elif any(phrase in text for phrase in [
        "because of", "as a result", "cause behind",
        "due to", "causing", "leads to", "affected by",
        "resulting in"
    ]):
        ai_rst.at[i, "Role"] = "Satellite"
        ai_rst.at[i, "Relation"] = "Cause"
        ai_rst.at[i, "Confidence"] = 0.75


    elif any(word in text for word in [
        "but", "however", "although", "while", "yet"
    ]):
        ai_rst.at[i, "Role"] = "Nucleus"
        ai_rst.at[i, "Relation"] = "Contrast"
        ai_rst.at[i, "Confidence"] = 0.70


    elif any(word in text for word in [
        "region", "africa", "ethiopia", "somalia",
        "kenya", "north africa", "sahara", "sahel"
    ]):
        ai_rst.at[i, "Role"] = "Satellite"
        ai_rst.at[i, "Relation"] = "Background"
        ai_rst.at[i, "Confidence"] = 0.65


    else:
        ai_rst.at[i, "Role"] = "Satellite"
        ai_rst.at[i, "Relation"] = "Elaboration"
        ai_rst.at[i, "Confidence"] = 0.50


ai_rst

,Unit_ID,Text,Role,Relation,Confidence
0,1,Even camels can't cope: Africa's ships of the desert hit by rising temperatures,Satellite,Background,0.65
1,2,"For centuries, the camel has been the ultimate survivor of Africa's drylands — an animal so well...",Satellite,Evidence,0.80
2,3,"The animal renowned as the ""ship of the desert"" evolved to withstand extreme temperatures, water...",Nucleus,Contrast,0.70
4,4,"Hassan Abdi Nur has kept camels in Kenya's Marsabit County for most of his life, following a rou...",Satellite,Background,0.65
5,5,"""My father used to know exactly when the rains would come and where the grass would be green,"" N...",Satellite,Elaboration,0.50
6,6,"Nur said he lost four camels during the drought that struck the region between 2020 and 2023, on...",Satellite,Background,0.65
7,7,"""We always said the camel does not die of thirst like other animals,"" he said. ""But I have seen ...",Nucleus,Contrast,0.70
8,8,Herders in neighbouring Somalia and Ethiopia's Somali region describe similar experiences. In pa...,Nucleus,Contrast,0.70
10,9,Herders' testimony is increasingly backed by scientific data. Meteorological records for the Hor...,Satellite,Evidence,0.80
11,10,"Regional climate monitoring bodies, including IGAD's Climate Prediction and Applications Centre,...",Satellite,Cause,0.75
12,11,"""We used to think of camels as almost drought-proof animals,"" said Dr Amina Yusuf, a veterinary ...",Satellite,Evidence,0.80
13,12,"Camel populations in parts of the Horn of Africa have continued to grow in absolute numbers, par...",Satellite,Evidence,0.80
15,13,"Camels are, by any measure, extraordinarily well suited to hot, dry environments. They can toler...",Satellite,Elaboration,0.50
16,14,"These adaptations, however, are calibrated to a particular range of conditions — conditions that...",Satellite,Evidence,0.80
17,15,"""The issue is not simply that it is hot — deserts have always been hot,"" explained Professor Ber...",Satellite,Elaboration,0.50
18,16,"Reduced, less predictable rainfall also affects the quality and availability of forage. Camels a...",Satellite,Elaboration,0.50
20,17,While the Horn of Africa has drawn particular attention because of the severity of its recent dr...,Satellite,Cause,0.75
21,18,"In Somalia, where camels are central to the rural economy and national identity, officials and a...",Satellite,Evidence,0.80
22,19,"Further north, in parts of the Sahara and Sahel, herders and researchers describe a slower but c...",Satellite,Evidence,0.80
23,20,"""What we are seeing is not confined to one country or one drought cycle,"" said Dr Yusuf. ""It is ...",Satellite,Background,0.65
25,21,Veterinarians and researchers point to several interlinked biological effects when camels are ex...,Satellite,Evidence,0.80
26,22,Dehydration is the most immediate concern. Although camels tolerate significant fluid loss compa...,Nucleus,Contrast,0.70
27,23,"Heat stress also appears to suppress immune function, making camels more susceptible to disease....",Satellite,Evidence,0.80
28,24,"Milk production, a critical resource for pastoralist households, is particularly sensitive to he...",Satellite,Elaboration,0.50
29,25,Reproductive performance is also affected. Camels already have long gestation periods and low re...,Satellite,Evidence,0.80
30,26,"Taken together, these effects — dehydration, disease, reduced milk yield, reproductive setbacks ...",Satellite,Elaboration,0.50
32,27,The implications extend well beyond individual animals. Camels underpin the economies of pastora...,Satellite,Evidence,0.80
33,28,"There are also social and cultural dimensions. In many pastoralist societies, camel ownership is...",Satellite,Background,0.65
34,29,"""When people lose their camels, they are not just losing an economic asset,"" said Fatuma Ali War...",Satellite,Background,0.65
36,30,Climate projections for the Horn of Africa generally point towards continued warming and greater...,Satellite,Evidence,0.80
37,31,Efforts to respond are already under way. Veterinary services in some areas have expanded mobile...,Satellite,Evidence,0.80
38,32,"""There is no single solution,"" said Professor Kiptoo. ""It will require better veterinary support...",Nucleus,Contrast,0.70
39,33,"Some researchers also point to the need for policies supporting herder mobility, noting that res...",Satellite,Evidence,0.80
41,34,"For Hassan Abdi Nur, the technical explanations matter less than what he sees on the ground. He ...",Satellite,Elaboration,0.50
42,35,"""We are not giving up on the camel,"" he said. ""It is still the best animal for this land. But we...",Nucleus,Contrast,0.70
43,36,His words capture the wider story now unfolding across Africa's drylands. The camel remains one ...,Nucleus,Contrast,0.70

In [21]:
# Convert the AI RST analysis table to Markdown and download it

from google.colab import files


ai_rst_md = ai_rst.to_markdown(index=False)


md_path = "/content/ai_rst_analysis.md"

with open(md_path, "w", encoding="utf-8") as f:
    f.write(ai_rst_md)


files.download(md_path)